version: '3.7'
services:
  backend:
    build: ./backend
    volumes:
    - ./backend:/app
    ports:
     - 8001:8001
  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/app
    ports:
      - 80:80